# For more information: https://github.com/julien-r44/adonis-sail
version: '3'
name: "records"
services:
  mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: records_mailhog
    ports:
      - '${MAILHOG_PORT:-1025}:1025'
      - '${MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sailredis:
  sailpgsql:
  sailminio:
  sailmongo:
